export const LEARNER_TOKEN_SERVICE = Symbol('LEARNER_TOKEN_SERVICE');
export const LEARNER_COOKIE_OPTS = Symbol('LEARNER_COOKIE_OPTS');
export const PROJECT_REPOSITORY = Symbol('PROJECT_REPOSITORY');
